### ISSUE TITLE
[ALM Accelerator - DOCS]: AA4PP July Release Docs Update

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#2897]
### Is your feature request related to a problem? Please describe.

Placeholder for required Doc updates in the July release

### Describe the solution you'd like

- [x] Need to incorporate additional permissions related settings in docs along with what we currently have for the Build Service Account to include access to resources as mentioned in this issue https://github.com/microsoft/coe-starter-kit/issues/2558 
- [x] CoE CLI Docs Update to specify Azure CLI version https://github.com/microsoft/coe-starter-kit/issues/2849
- [x] Docs on extensibility (Hooks).
- [x] Fix broken links to sample deployment configuration json files https://github.com/microsoft/coe-starter-kit/issues/3051
- [x] Clarify AAD Group team in deployment profile configuration https://github.com/microsoft/coe-starter-kit/issues/3064
- [x] Correct solution name in docs for ALM Acc. for Makers https://github.com/microsoft/coe-starter-kit/issues/3120

Will not make it for the July release
- [ ] App Registration / Service Connection configuration documentation related to https://github.com/microsoft/coe-starter-kit/issues/2649

Duplicate for above. Issue closed
- [ ] Docs update - Describe Service Principle https://github.com/microsoft/coe-starter-kit/issues/2676
