### ISSUE TITLE
[ALM Accelerator - Feature]: Configurable Pipelines

### ISSUE THREAD

**Issue by mikefactorial** [microsoft/coe-starter-kit#3495]
### Is your feature request related to a problem? Please describe.

Currently, it's not possible to configure deployment pipelines with more or less than three stages and the ability to host export,import, delete pipelines in a seperate project/repo is not possible. We need to add flexibility to the deployment pipeline generation as well as where the export, import, delete pipelines are hosted in an organization.

### Describe the solution you'd like

A user should be able to modify the deployment steps associated with a profile to include / exclude the standard validation, test and production pipelines. This also means that users should be able to include development environments in their deployment profile in order to provide a means to generate development environment deployment configurations to use on import of an unmanaged solution. 

An environment tagged as a development environment will not create deployment pipelines but will persist the deployment configuration. It will also need to generate an environment specific import pipeline to persist the build variables for replacement. To avoid this overhead we can provide an option to not use placeholders, but need to be clear that this is a potential security concern since all values will be saved as plain text in the deployment configuration json that is stored in source control.

Finally, we need to provide a "bring your own pipeline template" to support the above functionality. The goal is to allow users to create their own pipeline templates and specify the template yml on the deployment step that exists in their pipeline repository. This will make the deployment profiles extensible by allowing users to create their own templates to be used when deployment pipelines are generated. The expectation is that these pipelines will use similar placeholders to the following templates

https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/build-deploy-validation-SampleSolution.yml
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/build-deploy-test-SampleSolution.yml
https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/build-deploy-prod-SampleSolution.yml

e.g. BranchContainingTheBuildTemplates, RepositoryContainingTheBuildTemplates, SampleSolutionName

The cli will be responsible for replacing these placeholders based on the values sent to the export pipeline.

- [ ] https://github.com/microsoft/coe-starter-kit/issues/3212
- [ ]  https://github.com/microsoft/coe-starter-kit/issues/1152
- [ ]  https://github.com/microsoft/coe-starter-kit/issues/2277
- [ ] https://github.com/microsoft/coe-starter-kit/issues/2351
- [ ] https://github.com/microsoft/coe-starter-kit/issues/2541

**Comment by CoEStarterKitBot** [comment]
@mikefactorial This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
