### ISSUE TITLE
[CoE Starter Kit - Feature]: DLP Impact Analysis - UX and feature update

### ISSUE THREAD

**Issue by manuelap-msft** [microsoft/coe-starter-kit#5893]
### Is your feature request related to a problem? Please describe.

The growing adoption of Power Platform, and customer requirements to effectively clean up and mitigate risk during data policy changes meant that the DLP Editor v2 has become out of date and not meeting the needs of our customer base. 

### Describe the solution you'd like

The re-work consists of:

**Phase 1:**

- [x] UX update with Creator Kit components
- [x] multi-select / select all for moving connectors and environments into new categories
- [x] export results to task list to manage status separately
- [x] manage performance better through delegation > only show top 2000 apps/flows that are analyzed, for rest > export to CSV or task list
- [x] update export to CSV flow to also enable export to a dataverse table (task list) 
- [x] single email to one maker with impact on their app/flow

**Phase 2:**

- [ ] Save policy changes as draft so they can be applied later
- [ ] Workflows to work of the DLP Impact Analysis task list to, e.g. automatically delete resources, send approvals to makers, manage status
- [ ] Update command bar of dlp task list table to remove unneeded commands
- [ ] multi-select to email more makers with impact
- [ ] re-run the analysis on current environments

**Comment by manuelap-msft** [comment]
Outstanding work for Phase 1:

- [ ] add HTTP etc connectors in
- [ ] environment scope (all / except / include) 
- [ ] email makers > dynamically add impact for each email
- [ ] clean up flow to delete impact analysis task list after 30 days if no status has been set / status is complete

**Comment by manuelap-msft** [comment]
Phase 2:

- [ ]  Save policy changes as draft so they can be applied later
- [ ]  Workflows to work of the DLP Impact Analysis task list to, e.g. automatically delete resources, send approvals to makers, manage status
- [ ]  Update command bar of dlp task list table to remove unneeded commands
- [ ]  multi-select to email more makers with impact
- [ ]  re-run the analysis on current environments

**Comment by CoEStarterKitBot** [comment]
@manuelap-msft This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
